ccflags-y += -I$(srctree)/mediatek/custom/common/kernel/imgsensor/inc/
ccflags-y += -I$(srctree)/mediatek/custom/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/kernel/camera/camera/
ccflags-y += -I$(srctree)/mediatek/custom/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/kernel/dct/dct/

obj-y	+= mt9m114yuv_Sensor.o
