obj-$(CONFIG_CUSTOM_KERNEL_ACCELEROMETER)	+= accelerometer/

obj-$(CONFIG_CUSTOM_KERNEL_ALSPS)		+= alsps/

obj-y						+= cam_cal/

obj-y						+= eeprom/

obj-y						+= flashlight/

obj-$(CONFIG_CUSTOM_KERNEL_GYROSCOPE)		+= gyroscope/

obj-y						+= imgsensor/

obj-y						+= lcm/

obj-y						+= lens/

obj-$(CONFIG_CUSTOM_KERNEL_MAGNETOMETER)	+= magnetometer/

obj-$(CONFIG_MTK_SOUND)				+= sound/

obj-$(CONFIG_CUSTOM_KERNEL_SSW)			+= ssw/

obj-$(CONFIG_MTK_TOUCHPANEL)			+= touchpanel/

# The Makefile in the usb/src/ directory does not have to be taken into account
# here nor in mediatek/custom/mt6589/kernel/usb/, as it just adds two include
# directories that are irrelevant to build mtk_usb_custom.c.
