ccflags-y += -I$(srctree)/mediatek/custom/common/kernel/imgsensor/inc/
ccflags-y += -I$(srctree)/mediatek/custom/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/kernel/dct/dct/

obj-y	+= dummyds.o kd_camera_hw.o
