obj-$(CONFIG_CUSTOM_KERNEL_ACCELEROMETER)	+= accelerometer/

obj-$(CONFIG_CUSTOM_KERNEL_ALSPS)		+= alsps/

obj-y						+= camera/camera/

obj-y						+= core/src/

obj-y						+= dct/dct/

obj-y						+= flashlight/

obj-$(CONFIG_CUSTOM_KERNEL_GYROSCOPE)		+= gyroscope/

obj-y						+= imgsensor/

obj-$(CONFIG_MTK_KEYPAD)			+= kpd/kpd/

obj-$(CONFIG_MTK_LEDS)				+= leds/mt65xx/

obj-$(CONFIG_CUSTOM_KERNEL_MAGNETOMETER)	+= magnetometer/

obj-$(CONFIG_MTK_VIBRATOR)			+= vibrator/
