ccflags-y += -I$(srctree)/mediatek/custom/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/kernel/dct/dct/
ccflags-y += -I$(srctree)/mediatek/custom/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/kernel/vibrator/

obj-$(CONFIG_MTK_VIBRATOR) := vibrator.o
#ccflags-y := -Idrivers/staging/android/
