ccflags-y += -I$(srctree)/mediatek/custom/common/kernel/touchpanel/src/
ccflags-y += -I$(srctree)/mediatek/custom/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/kernel/core/src/
ccflags-y += -I$(srctree)/mediatek/custom/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/kernel/dct/dct/
ccflags-y += -I$(srctree)/mediatek/custom/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/kernel/touchpanel/ft5316/

obj-y	+= focaltech_ctl.o ft5316_driver.o ft6x06_ex_fun.o
