ccflags-y += -I$(srctree)/mediatek/custom/common/kernel/cam_cal/inc/
ccflags-y += -I$(srctree)/mediatek/custom/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/kernel/camera/camera/
ccflags-y += -I$(srctree)/mediatek/custom/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/kernel/dct/dct/

obj-y	+= dummy_cam_cal.o
