ccflags-y += -I$(srctree)/mediatek/custom/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/kernel/core/src/
ccflags-y += -I$(srctree)/mediatek/custom/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/kernel/dct/dct/

obj-y	+= mtk_tpd.o tpd_button.o tpd_calibrate.o tpd_debug.o tpd_default.o tpd_init.o tpd_misc.o tpd_setting.o
